var searchData=
[
  ['savew_0',['SaveW',['../class_save_w.html',1,'']]],
  ['searchwidget_1',['SearchWidget',['../class_search_widget.html',1,'SearchWidget'],['../class_ui_1_1_search_widget.html',1,'Ui::SearchWidget']]],
  ['serializer_2',['serializer',['../classdetail_1_1serializer.html',1,'detail']]],
  ['session_3',['Session',['../classopenai_1_1__detail_1_1_session.html',1,'openai::_detail']]],
  ['settingswidget_4',['SettingsWidget',['../class_settings_widget.html',1,'SettingsWidget'],['../class_ui_1_1_settings_widget.html',1,'Ui::SettingsWidget']]],
  ['settingswindow_5',['SettingsWindow',['../class_settings_window.html',1,'']]],
  ['should_5fstringify_5fas_5funderlying_5ftype_6',['should_stringify_as_underlying_type',['../structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html',1,'doctest::detail']]],
  ['sidepanel_7',['SidePanel',['../class_side_panel.html',1,'']]],
  ['span_5finput_5fadapter_8',['span_input_adapter',['../classdetail_1_1span__input__adapter.html',1,'detail']]],
  ['spike_9',['Spike',['../classspike_1_1_spike.html',1,'spike']]],
  ['static_5fconst_10',['static_const',['../structdetail_1_1static__const.html',1,'detail']]],
  ['string_11',['String',['../classdoctest_1_1_string.html',1,'doctest']]],
  ['string_5ft_5fhelper_12',['string_t_helper',['../structjson__pointer_1_1string__t__helper.html',1,'json_pointer']]],
  ['string_5ft_5fhelper_3c_20nlohmann_5fbasic_5fjson_5ftpl_20_3e_13',['string_t_helper&lt; NLOHMANN_BASIC_JSON_TPL &gt;',['../structjson__pointer_1_1string__t__helper_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html',1,'json_pointer']]],
  ['stringcontains_14',['StringContains',['../classdoctest_1_1_assert_data_1_1_string_contains.html',1,'doctest::AssertData']]],
  ['stringmaker_15',['StringMaker',['../structdoctest_1_1_string_maker.html',1,'doctest']]],
  ['stringmakerbase_16',['StringMakerBase',['../structdoctest_1_1detail_1_1_string_maker_base.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20detail_3a_3ahas_5finsertion_5foperator_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5fpointer_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5farray_3c_20t_20_3e_3a_3avalue_20_3e_17',['StringMakerBase&lt; detail::has_insertion_operator&lt; T &gt;::value||detail::types::is_pointer&lt; T &gt;::value||detail::types::is_array&lt; T &gt;::value &gt;',['../structdoctest_1_1detail_1_1_string_maker_base.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20true_20_3e_18',['StringMakerBase&lt; true &gt;',['../structdoctest_1_1detail_1_1_string_maker_base_3_01true_01_4.html',1,'doctest::detail']]],
  ['style_19',['Style',['../class_style.html',1,'']]],
  ['subcase_20',['Subcase',['../structdoctest_1_1detail_1_1_subcase.html',1,'doctest::detail']]],
  ['subcasesignature_21',['SubcaseSignature',['../structdoctest_1_1_subcase_signature.html',1,'doctest']]]
];
